baseURL: https://taboza.dev
languageCode: pt-BR
title: taboza.dev
theme: ["PaperMod"]
enableRobotsTXT: true

# Disable taxonomies temporally (categories and tags)
taxonomies: {}

params:

  profileMode:
    enabled: true
    title: Paulo T. Nascimento
    imageUrl: 451f7e89247904160e086c31b96821a00aa8c4f33ffedda0c92933ea68b78bc3.jpg
    imageTitle: Foto de Paulo

  socialIcons:
    - name: linkedin
      url: https://www.linkedin.com/in/plnsc
    - name: bluesky
      url: https://bsky.app/profile/taboza.dev
    - name: telegram
      url: https://t.me/plnsct
    - name: github
      url: https://github.com/plnsc
    - name: gitlab
      url: https://gitlab.com/plnsc

  assets:
    favicon: /favicon.ico
    favicon16x16: /favicon.ico
    favicon32x32: /favicon-32x32.ico

  label:
    icon: /pe-de-acerola-32x32.webp
    iconHeight: 32
