name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-build:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go
        run: go build ./...

  nix-build:
    name: Nix Build
    runs-on: ubuntu-latest
    needs: go-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Build with Nix
        run: nix build
