name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Setting up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Building with Go
        run: go build ./...

      - name: Setting up Nix
        uses: cachix/install-nix-action@v25

      - name: Building with Nix
        run: nix build

  test:
    name: Go Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Installing Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Running tests with Go
        run: go test -v ./...

      - name: Installing Nix
        uses: cachix/install-nix-action@v25

      - name: Running tests with Nix
        run: nix build
