name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Go tests
        run: go test -v ./...

  nix-test:
    name: Nix Test
    runs-on: ubuntu-latest
    needs: go-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Run Nix tests
        run: nix flake check
